on:
  push:
    branches: main
name: azure-infrastructure-cd
permissions:
  id-token: write
  contents: read
jobs:
  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: deploy storage account
        id: deploy_storage_account
        uses: azure/arm-deploy@v2
        with:
          scope: 'subscription'
          template: './resource_group/main.bicep'
          region: 'westeurope'
          parameters: name=sampleInfra
