on:
  push:
    branches: main
name: azure-infrastructure-cd
permissions:
  id-token: write
  contents: read
  security-events: write
jobs:
  quality_checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Lint Bicep
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az bicep install
            az bicep lint --file ./deploy/main.bicep --diagnostics-format sarif > bicep.sarif

      - name: Upload SARIF
        if: (success() || failure())
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: bicep
          sarif_file: bicep.sarif

  infrastructure:
    needs: quality_checks
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: deploy storage account
        id: deploy_storage_account
        uses: azure/arm-deploy@v2
        with:
          scope: 'subscription'
          template: './deploy/main.bicep'
          region: 'westeurope'
